### ISSUE TITLE
Where to find the Setting for opening csv with Collabora #671 ?

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/richdocuments#1224]
Dear All,

in #671 it reads like the possibility to open .csv always with Collabora was added

I wasn't able to find the Setting to force that behaviour to open .csv always with Collabora

Could you give me a hint, or is this a bug?

**Comment by thebearon** [comment]
Opening CSVs with CODE/Collabora Online directly isn't the best experience, anyway, because the workflow of importing them into a regular spreadsheet isn't implemented. You're better off copying the content from a text editor to clipboard, and pasting it in Collabore Online, which triggers the Text Import dialog where you can choose how the CSV is interpreted.

**Comment by githubkoma** [comment]
> Opening CSVs with CODE/Collabora Online directly isn't the best experience, anyway, because the workflow of importing them into a regular spreadsheet isn't implemented. You're better off copying the content from a text editor to clipboard, and pasting it in Collabore Online, which triggers the Text Import dialog where you can choose how the CSV is interpreted.

many thanks for that hint!

**Comment by juliushaertl** [comment]
Let's close this as a won't fix for now. Once there is a more sane way to import csv into COOL we can reconsider opening it by default.
