### ISSUE TITLE
Additional templates for Collabora Online

### ISSUE THREAD

**Issue by kendy** [nextcloud/richdocuments#1306]
@juliushaertl: We've got a report that we should expose the LibreOffice / core templates in Collabora Online too: https://github.com/CollaboraOnline/online/issues/1021

What is your view there, please?  One of the ideas was that we might introduce an endpoint in Collabora Online that would advertise the available templates & their URLs, and serve it for the new documents creation.  Then the Nextcloud UI could show these as possibilities too, in addition to those that are defined in richdocuments.

What do you think?

**Comment by juliushaertl** [comment]
Yes that would definitely be nice. However I personally think we should rather just add them to the Nextcloud template management we already have in place rather than introducing another back-channel that might complicate things on both sides. This would also allow the admins to remove them if wished. 

My idea there would be to have them added by default to the global templates similar to the empty ones, but with the option to remove them as an admin:
![image](https://user-images.githubusercontent.com/3404133/104024594-a2660680-51c3-11eb-9b22-4f759d767c46.png)

What do you think about that?

**Comment by juliushaertl** [comment]
Of course i also see your point in reducing the maintenance work if you can just easily pull them into COOL as stated in https://github.com/CollaboraOnline/online/issues/1021

**Comment by kendy** [comment]
@juliushaertl: Thanks for the feedback, unfortunately I am a bit unsure if it was a "go ahead" from you, or not really :-)

I mean - I'm perfectly fine with having the UI implemented so that it is indistinguishable if the template comes as bundled in richdocuments, or if it is pulled from Collabora Online.  The possibility to disable some by the admin sounds great to me too.

But I am not sure if you meant that we should rather copy such templates to richdocuments during packaging & distribute that way, or if the idea of pulling them directly from a COOL endpoint is OK for you?

Of course, if you are fine with pulling from the endpoint in general, it's completely up to you if / how you download & cache them, allow disabling, etc.  There is only one danger - that they might change with COOL updates, so checking the content of the advertising endpoint might be necessary from time to time.

**Comment by juliushaertl** [comment]
@kendy I was thinking about this a bit more also because we have been working on a more standardized way of handling templates inside of Nextcloud (see https://github.com/nextcloud/server/pull/25090) where we basically introduce a way that allows users to have their own template directory by the server and copy over the template to the new file. Now this has a fallback for app provided templates as they are currently available in richdocuments that requires the templates to be stored in the appdata storage, so we need some custom handling to copy over those files even if we would ship them with richdocuments. Considering this I think just having the templates provided by COOL makes the most sense. We also don't have the issue of maintaining the template files in two places then.

So to break this down into a rough plan, this is what i'd imagine:
- COOL has an API endpoint that lists templates and provides
  - A way to download the file
  - A way to generate a preview (could just be the convert-to endpoint with the downloaded file i assume)
  - A way to detect if templates have been updated (maybe just the COOL version number)
  - I'd assume each template has a unique filename so we can properly track them on the Nextcloud side
- richdocuments will fetch the templates and store them inside of appdata
  - The templates will be exposed system-wide into the new template API https://github.com/nextcloud/richdocuments/pull/1317/files#diff-9b958d8b7d92f270945373bdf7fa6c5a3065f7f0749a6c78c1ceb05ef165cfb6

cc @jancborchardt Since this would basically add more templates by default if Collabora is installed and we currently just had plans for hand-crafted templates that would be provided to the users after first login as kind of example templates.

**Comment by jancborchardt** [comment]
> Since this would basically add more templates by default if Collabora is installed and we currently just had plans for hand-crafted templates that would be provided to the users after first login as kind of example templates.

Yeah, so a big reason why we specifically did templates on our own was that we weren’t super happy with the design of existing templates we could find. @kendy are there any screenshots or a directory of the current templates?

As Julius also mentioned, I’d rather have us offer few great and simple templates by default (the 2–3 per app type that we do now), which can be used to quickly get started, but also serve as a way to demo the template mechanism.

**Comment by juliushaertl** [comment]
Lets close this then I'd say. If there are specific templates that might be interesting to add to our default set we could discuss them individually at https://github.com/nextcloud/example-files
