### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'registerSection' of undefined     at files.js:41

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/richdocuments#1351]
When accessing a public shared file (e.g. `test.md`), I get the following JS error:

```
files.js:41 Uncaught (in promise) TypeError: Cannot read property 'registerSection' of undefined
    at files.js:41
(anonymous) @ files.js:41
Promise.then (async)
(anonymous) @ files.js:40
```

**Comment by juliushaertl** [comment]
Does not seem to happen on my test system and the registerSecion is never called in richdocuments. Where did that occur, looks familiar to what was recently fixed with the latest groupfolders release:

https://github.com/nextcloud/groupfolders/commit/5b2adbd41fdd70532b8df3e1d9cdd98b9e04b0b1#diff-6653fe3a8ac35dad2e28ef2134d921749c4334d4b81a593f80ae312cde95df4eR34

**Comment by juliushaertl** [comment]
Ah just noticed that this was 22 days ago, so I assume that would be fixed now.

**Comment by LukasReschke** [comment]
I don't see it anymore either on c.nc.c
