### ISSUE TITLE
Public Link always opens Collabora

### ISSUE THREAD

**Issue by tilllt** [nextcloud/richdocuments#1354]
Maybe i missed something in the docs, but publicly sharing a document that can be handled by Collabora will always open it in Collabora when the external user clicks on the link. 

That is not always desirable: i just sent Presentation to a client and the presentation should just download, i dont want it to show in the browser. 

So - i am not sure if this is a bug, a feature request or an oversight from me, but i think both types of external shares should be possible somehow.

**Comment by matthijskooijman** [comment]
I'm actually seeing the *inverse* of this when sharing an "internal link" - then the folder is opened with the shared file selected in the sidebar, but I would prefer that the document would just open in Collabora directly (especially since with multiple similar and long filenames, it is not immediately or at all obvious which file was linked to).

So maybe this suggests that (both) these links should go to some intermediate page that has a "download" and "edit" button, and/or you should be able to select on link generation which of these actions the link should do?

See also #1313, which is somewhat related.

**Comment by tilllt** [comment]
The problem is not that you cannot download the file, you can, like you said, there is a button on the upper right corner. for privacy and user experience reasons, sometimes i DONT want a document to open as a preview in the users browser. On top of that, a lot of people unfamiliar with Nextcloud will not realize there IS a download button. This happens to me very frequently. I appreciate you taking your time to answer my issue, but it doesn't help if you label an obvious UX problem as "non existent". 

I don't think that's the way to get rid of issues.

**Comment by matthijskooijman** [comment]
Additionally, it's useful if there is a way to modify links to e.g. force a download, but in practice, most users will not realize this unless there is also a UI to generate them. In that context, adding e.g. `/download` is something that I could tell my users and they might remember, but telling them to hand-construct an url in the form of `https://cloud.yourcloud.com/apps/files/?dir=/folder&view=-shared&openfile=(file-ID)` is definitely too much for most of my users, so having a UI to generate the appropriate flavor of link still seems to be an unsolved request (though maybe it was not previously articulated as such).
