### ISSUE TITLE
Default mimetype actions

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#1400]
Currently csv is opened by default on Collabora, however we also register text/csv as a default in the text app. As we do not have a way to customize which app should be used by the user or admin basically the app that registers as the last one at runtime of the javascript code will win and be the default, which is not really a good option imo.

@jancborchardt I know how you think about configuration options for default file actions but there are cases where certain organizations have the need to enforce either one or the other app for a given mimetype. I assume having something like operating systems do where the user can set a new default file opener is a bit to much here, but still think we should tackle this in some way.

I was wondering if we should think about introducing a matrix configuration so that at least the admin can define which mimetypes the app should open by default, similar to how the ONLYOFFICE app does it already:

![image](https://user-images.githubusercontent.com/3404133/109783505-5c00b700-7c0a-11eb-9c85-0e78b9bea4aa.png)

**Comment by jancborchardt** [comment]
Couldn’t we have some sort of ranking for each of the filetypes? E.g. all of OnlyOffice, Collabora Online and Text might register for all sorts of mimetypes, but there’s a clear best choice for each, between either the full OnlyOffice/Collabora, or simple Text.
- For all the doc*, xl*, pp*, od*, ot* file types it’s clearly OnlyOffice/Collabora
- In the case of CSV you mention, it would be OnlyOffice/Collabora cause that gives you the proper table layout. That’s a much nicer and accessible view
- For txt it’s basically always Text?
- Essentially we could say that maybe in all cases except .md and .txt, OnlyOffice/Collabora can take precedence if they are registered on that file type, no?

Possible issues:
- People might want to open CSV in plain text, but we could also skip over this for now as it is about the default, and it should always be possible to copy paste it from outside of Collabora/OnlyOffice
- For PDF, the files_pdfviewer should always be used – but maybe people want to edit the file in ways which is not possible in that app?

-----

Otherwise yeah, we could add a similar matrix like OnlyOffice has to Collabora. Or maybe better a central list like Gnome and other operating systems do, which makes it more obvious if a filetype is missing an app to open with:
![image](https://user-images.githubusercontent.com/925062/113276500-2cfc6480-92e0-11eb-8dca-ef05f970a299.png)

**Comment by Thatoo** [comment]
We miss this option too. Sometime .docx are opening in collabora whereas we'd rather have them opened in onlyoffice and keep collabora for .odt files only. Same with .ods/.xlsx and .odp/.pptx .
Onlyoffice, as the image shown by @juliushaertl , offers the option to open only .docx, .xlsx and .pptx .
I hope collabora could have an option, as an admin, to choose to open only .odt, .ods, .odp.

**Comment by skynick11** [comment]
>  Sometime .docx are opening in collabora whereas we'd rather have them opened in onlyoffice and keep collabora for .odt files only

Moreover, I have seen situations when .docx (.xlsx, etc.) in the browser are opened in Collabora, but in the mobile client they are opened in Onlyoffice - with the same NC21 server (where both Collabora and Onlyoffice applications are installed). .. 

Therefore, I think it would be nice to be able to explicitly specify which file types should be opened by which particular application.

**Comment by cetcondor** [comment]
Additional information: it seems that the existing rules are anyway not followed everywhere in Nextcloud. In the default Dashboard, under the section Empfohlene Dateien/Recommended Files when there's a CSV file, it's opened with the text editor instead of Collabora, which is used throughout the files browser. 

Tested today on two NC 21.0.3 with all latest app updates on different servers of different organisations.

**Comment by pierreozoux** [comment]
I wanted to open a bug, but I see this issue so I'll plug myself here.

Tested today on a 20.0.12 freshly updated instance.

I open a docx with onlyoffice, share it in read/write, and open this link in an other browser.
It is then opened with lool.

I find it surprising for the user, as the collaboration will definitely not work, so this looks like a bug to me, not an enhancement.

**Comment by vasyugan** [comment]
> I find it surprising for the user, as the collaboration will definitely not work, so this looks like a bug to me, not an enhancement.

Currently, the situation is such that you have to uninstall either collabora or OnlyOffice to make sure that collaboration works. For me, this means that I have to uninstall Collabora, because many users have complained to me about its laggy interface, whereas OpenOffice is much more responsive, due to client side rendering. So, for me for now this means I have to uninstall Collabora because I can't find a reliable way of preventing it from usurping the OOXML file association.

**Comment by vasyugan** [comment]
I would strongly argue for closing it in favour of [#29017](https://github.com/nextcloud/server/issues/29017). We don't want yet another file hander configuration gui shipped by the richdocuments app. Instead, there should be one central, app independent place in the Nextcloud admin gui, plus a user level configuration gui.

**Comment by rosa2** [comment]
hello
I am having the same problem: we have Collabora for people that uses LibreOffice and OnlyOffice for people that uses Microsoft Office. Since the last update to NextCloud 22.2.0 all documents are open with Collabora.

Please, make a generic place where apps can register the mime types that they can handle and users or administrators with shell can choose.

Does anybody know where an administrator can change this, please? Thanks for the tip and for making NextCloud :)

**Comment by pierreozoux** [comment]
We ended up doing a dirty patch:
https://lab.libreho.st/libre.sh/docker/nextcloud/-/merge_requests/12/diffs#diff-content-dc5ea057fcb8783df59ef97caf2fa02971550316

Our use case is quiet simple, our users want to run LibreOfficeOnline and ONLYOFFICE side by side.
We decided that LibreOfficeOnline will only have access to its mime types, and that's it.

We'd like to offer an half baked solution, instead of the fully fledged real, configurable list of mimetype.

Would you accept if we PR to add a conf like a bool `richdocument_minimum_mimetype`, and if set to true, would only allow the minimum list, and if not set, or set to false, would keep the current behavior?

Would you like this idea? If yes, then we could make a PR for that, we'd prefer than maintaining our dirty patch ;)

**Comment by rosa2** [comment]
Thanks pierreozoux
I saw how you solved it and I copied the solution removing from lib/Capabilities.php the OnlyOffice formats.
Very nice your solution multioffice. Are you thinking on uploading it in https://apps.nextcloud.com ?

Please, make an interface where admins can choose what it is best suit for their NextCloud installation :pray:

**Comment by pierreozoux** [comment]
@rosa2 I'll hide my comment as this will be offtopic, but to make it clean, we'd need to properly create an "API" for this kind of menu to happen in Nc.
And then apps like oo could create this kind of menu.
But this app is a really dirty hack, not sure that publishing it will serve anybody :/

**Comment by juliushaertl** [comment]
Since this requires a proper handling of mime type openers in the server, lets close it here and use https://github.com/nextcloud/server/issues/8105 for tracking and follow up discussions.
