### ISSUE TITLE
Bug in versioning with NC12 collabora online app 1.12.39

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/richdocuments#150]
Hi
There is a bug in versioning with CODE in NC 12.04

Versioning seems to work correctly, if the file is edited directly in a users directory. But when a file inside a shared directory is edited by another user, versioning is not working.

Then we get the following errors inside the log:

Error | PHP | copy(/nextcloud_data/logged-in-user/shared-directory/file.odt): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#272
-- | -- | --

**Comment by reneglauser** [comment]
Hi,
I just analysed the situation again. The problem is not related to the shared folder but to the configuration of our external storage.

We have the following configuration:
- Local folder "/mnt/data" mounted as external storage of type "local" in Nextcloud.
- Shared the subfolder "/mnt/data/subfolder" with another user inside Nextcloud
- Work on the file "/mnt/data/subfolder/file.odt" inside Nextcloud with Collabora

It realy seems to be a bug, that the versioning inside Collabore in this situation does not work. Versioning inside a "normal" shared folder inside the Nextcloud Data-Directory works as expected

**Comment by reneglauser** [comment]
Problem still remains in v 1.12.40
@thebearon should this be confirmed as bug or not?
