### ISSUE TITLE
Add option to pass in custom CSS for theming

### ISSUE THREAD

**Issue by adroslice** [nextcloud/richdocuments#1590]
**Is your feature request related to a problem? Please describe.**
I use a dark theme in my Nextcloud, and it's quite uncomfortable and eye straining to then open a document and almost the entire screen goes white.

**Describe the solution you'd like**
It would be most convenient to simply have the custom CSS statements in a textarea that can be edited in the admin settings. Alternatively, each variable could also have its own input field.
Reference:
https://www.collaboraoffice.com/uncategorized-nl/theming-of-collabora-online/

**Describe alternatives you've considered**
A hacky solution that would work for me, but not with all browsers, would be to use an extension and/or a userstyle.

**Additional context**
Alternative solutions to my problem would also be welcome.
EDIT: Right after submitting this issue I actually had a look at the inspector, and confusingly enough, saw that these variables don't actually seem to be in use.
![image](https://user-images.githubusercontent.com/20285224/120085096-9678d380-c0d5-11eb-9c99-5a39bddc28fd.png)

**Comment by top-logic** [comment]
There is an APP called "Custom CSS" that may can do it in a "hacky" way.
It will show up under administrative settings => desgin.
We use this to do simple stuff like this but it is maybe possible to do what you want:
`#contactsmenu {
  display: none;
}
#generate-backup-codes {
  display: none;
}`

**Comment by adroslice** [comment]
That won't work here, since Collabora in this case lives in an iframe. Styling of the containing document will not, and cannot affect the contents of the iframe. As far as I know, anyway.

**Comment by kendy** [comment]
@adroslice: Thank you for the report!  Are you building the Collabora Online from the sources?  Because on the screenshot, you are missing the theming that we ship with the CODE - which makes use of the variables passed by the Nextcloud integration - so the colors are preserved.

Having said that, Collabora Online cannot do a dark theme fully yet, due to the sidebar that is so far rendered as pixels on the server; but we are working on the problem.

Details about passing the variables: https://sdk.collaboraonline.com/docs/theming.html
