### ISSUE TITLE
Access forbidden when trying to open document

### ISSUE THREAD

**Issue by onny** [nextcloud/richdocuments#17]
### Steps to reproduce
1. Creating odt document
2. Opening it
3. Getting error "Access forbidden"

### Expected behaviour
Collabora Online should load the document and display it

### Actual behaviour
"Access forbidden" error message appears

### Server configuration
**Operating system**: ArchLinux x86_64
**Web server:** Nginx
**Database:** Mysql
**PHP version:** 7.1.1
**Nextcloud version:** 11.0
**Updated from an older Nextcloud/ownCloud or fresh install:** updated
**Where did you install Nextcloud from:** [AUR](https://aur.archlinux.org/packages/nextcloud/)

### Logs
* No logging appears in loolwsd (debug mode)
* At least there is one request on the loolwsd port when opening a document: tcpdump -i ens3 port 9980 -A 
```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens3, link-type EN10MB (Ethernet), capture size 262144 bytes
07:33:11.197640 IP http-new.51522 > mail1.project-insanity.org.9980: Flags [S], seq 2221071965, win 29200, options [mss 1460,sackOK,TS val 16188932 ecr 0,nop,wscale 7], length 0
E..<.Y@.@...
..r.    c4.B&..b.]......r.r..........
............
07:33:11.197843 IP mail1.project-insanity.org.9980 > http-new.51522: Flags [R.], seq 0, ack 2221071966, win 0, length 0
E..(i.@.@.^F.   c4
..r&..B.....b.^P.......
```
* Tried to allow every hostname combination in loolwsd.xml, still no luck

**Comment by ttr** [comment]
try to remove ending slash from url in admin settings :)

**Comment by onny** [comment]
Unfortunately, it didn't help :(

**Comment by tdesloovere** [comment]
Don't know if this will help you but I had sort of the same issue. It looked like Nextcloud was no longer redirecting office documents to the Collabora Online server (nothing appeared in the log file).

For me, the "solution/workaround" was, using the Apache Proxy method on the CollaboraOnline server. Apparently, adding a port in the URL of the Collabora Online configuration in Nextcloud, no longer works. So, if you set up the Proxy on your web service and just use the URL https://IPFQDN, it should work again.

For me this seems like a regression since Nextcloud version 10.0.4 and the Collabora Online App version 1.1.17 was working perfectly with the port added in the URL.

When setting up the proxy in you web service, be advised, for this issue: https://github.com/nextcloud/richdocuments/issues/21 (use the correct configuration on your web service.

greetings,

Tom

**Comment by powerriegel** [comment]
Same problem.

**Comment by hirokihara** [comment]
Same problem.

**Comment by victorbw** [comment]
Same problem.

**Comment by victorbw** [comment]
no dev around for this?

**Comment by Fankmann** [comment]
Same problem

**Comment by kerematam** [comment]
Same fucking problem.. 

Operating system: Ubuntu 16.04 x86_64
Web server: Apache
Database: Mysql
PHP version: v7.0.18
Nextcloud version: 11.0
Updated from an older Nextcloud/ownCloud or fresh install: fresh install
Where did you install Nextcloud from: [Web Installer](https://download.nextcloud.com/server/installer/setup-nextcloud.php)

**Comment by danger89** [comment]
Same problem...

Web server: Nginx
Nextcloud: 11
PHP 7.1

I tried many different kind of docker container settings and nginx proxy settings. I think I'm really doing to the right thing!

I keep getting access denied. Looking at the web logging, something about the SSL handshake does wrong :S?

```
2017/09/14 03:38:23 [error] 15895#15895: *1856 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 192.168.1.1, server: office.YOURDOMAIN.COM, request: "GET /hosting/discovery HTTP/1.1", upstream: "https://127.0.0.1:9980/hosting/discovery", host: "office.YOURDOMAIN.COM"
```

Strange since visiting my office subdomain gives me a correct let's encrypt certificate although returning 502 (going to /). I have no idea what I'm doing wrong here.. I tried both http as well as https within my Nginx settings.

**Comment by danger89** [comment]
@gabor-udvari What do I do wrong here? See above..

**Comment by kerematam** [comment]
I could only solve it via install script that is provided https://github.com/nextcloud/vm
I dont know where i am failing to configure but seem like this script fix it.

**Comment by danger89** [comment]
Which exact script? I'm not using a Raspberry pi nor using a VM actually. Plus I'm using Nginx and not apache webserver..

**Comment by danger89** [comment]
Well it was due to a crashing Docker instance (via `docker logs <id>` you can see that info).

See the solution here:
https://help.nextcloud.com/t/collabora-docker-capabilities-problem/4774/10?u=danger89

That fixed my problem.

**Comment by juliushaertl** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
