### ISSUE TITLE
Single file share links still has two header bars

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#1884]
With Nextcloud Office, a single file share link still has the duplicate header bar. In order to address this, we need:
- Scale the Collabora container to full size
   - This needs extra care in case Talk is enbabled and the Talk sidebar is present on shares
 - Make sure that the existing header actions (download, add to your nextcloud) are still there
 - The document itself should not have a close button (which currently gets back to just the preview and there is no way to reopen Office anymore)

As discussed with @jancborchardt

**Comment by juliushaertl** [comment]
- [ ] Sidebar button in collabora does not trigger the talk sidebar on public share links

**Comment by jancborchardt** [comment]
I would suggest to move this in To do because this really looks quite bad when sharing documents with others outside of Nextcloud like external partners. Duplicate logos, duplicate title, duplicate sidebar button of which one doesn’t work:

![image](https://user-images.githubusercontent.com/925062/176164969-a7129f83-61a6-4689-91d7-1f3e438759fe.png)
