### ISSUE TITLE
Activating 4.2.3 app slows down Nextcloud

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/richdocuments#1887]
Dear community,

I'm using Ubuntu 20.04.3 LTS with NGINX 1.21.4 as reverse proxy with PHP 8.0.13.
Nextcloud 22.2.3 works without problems, but when I actiate Collabora Online 4.2.3 the app slows down the whole Nextcloud-Instance.

Can someone help me with a hint?

Thanks

**Comment by SimplyCorbett** [comment]
What's the latency like to your collabora server? Are you running locally or is it some distance from the main server?

**Comment by kangaroo72** [comment]
It's a local Docker, but CPU & Memory are boring....
What I expected: The Nexcloud-Instance is remote. When Collabora Online is activated, the Firefox from my notebook will be flooded with memory....

**Comment by juliushaertl** [comment]
Maybe you can clarify your report a bit more, is your browser becoming slow or the Nextcloud instance itself? Also are you running the built-in code server or a docker code installation?

**Comment by kangaroo72** [comment]
Hi - thanks for investigating.
my browser ist getting unusable - is getting flooded by memory
I can still use SSH an the NC-machine without problems. HTOP shows no problems.
Even when I have no code server and no docker-image running, the problem exists.
To explain: I don't need CODE to slowdown - the app is enough.
I'm activating the app, and the system is braking :-(

**Comment by juliushaertl** [comment]
Can you check if that is just an issue in firefox or if other browsers are also affected? Is it only happening when opening a document or also when just loading the files list

**Comment by kangaroo72** [comment]
Now with Edge - same issue...
![grafik](https://user-images.githubusercontent.com/6906390/144932252-b32795a1-683b-4547-ab9a-2d8d8f7ea47d.png)

**Comment by kangaroo72** [comment]
totally crappy - even unable to load the version info ^^

**Comment by juliushaertl** [comment]
I see, can you maybe fill out the complete issue template and also provide the output of the `occ config:list` command. Further some additional details on your webserver setup would be interesting, especiallyhow Nextcloud is installed and  if you run a reverse proxy in front of it?

I assume this is somehow related to the autoconfiguration of the built-in code server in each of the requests, #1901 might fix that Nevertheless you could try to install a separate code server through https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html and manually remove the richdocumentscode app from your apps directory in order to get a working setup quickly.

**Comment by kangaroo72** [comment]
Dear @juliushaertl , again thanks for investigating. actually the whole system slows down, and I don't know why.
SSH is still accessible. I'll try to figure out. Maybe it's hardware-related...
I'm coming back to you. Thanks until here.
Cheers, -Tom-

**Comment by juliushaertl** [comment]
If you have ssh access you can temporarily move the app in apps/richdocumentscode to some other location and see if that makes the system responsive again together with a restart of the webserver/php-fpm.

**Comment by strongiukas** [comment]
I also have the same problem.
As soon as I enable "Collabora Office 4.2.3"app in NextCloud Appstore, the system becomes painfully slow. 
On Seetings page, Collabora Online Settings I get error: "Could not establish connection to the Collabora Online server"
For short period of time I could fix this by adding may domain to hosts file under 127.0.0.1. Sometimes it slows down, sometimes not.

What I see in logs is: 
richdocuments:
GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 45001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://subdomain.domain.com/apps/richdocumentscode/proxy.php?req=/hosting/discovery

**Comment by kangaroo72** [comment]
yaaaaaaay - I made a measure yesterday - 45 secs :-P

**Comment by strongiukas** [comment]
after some playing around, it looks like it is working OK, for now.
What I did: 
downgrading biuld-in CODE from 21.11.4 to 6.4.1103 - didn't help.
Then, with everything enabled I went to "Collabora Online Settings" and set "use demo server". 
Then, tried to set back to "use "built-in CODE", but, after waiting 45secs, it wrote me that it couldn't connect. 
Then, via SSH, I added a line to /etc/hosts   "1270.0.1 sub.domain.com" ; Restarted web server.
Then, again,   tried to set back to "use "built-in CODE", and succeeded. 
Difference in configuration of "occ config:list richdocuments" before there was only "wopi_url", but now there is also a "public_wopi_url"
I hope, this has fixed my problem for long.

**Comment by kangaroo72** [comment]
@strongiukas great job
Which versions you'r using now?
Richdocuments 5.0.0 and CODE 21.11.4? Or do you still use downgraded versions?

**Comment by strongiukas** [comment]
Well, it didn't help. Today, it sometimes work, sometimes not.
Will try to set Redis memcache.

**Comment by kangaroo72** [comment]
At least the performance from my Nextcloud-Instance is working again.
Collabora.... hmm... let's wait...

**Comment by kojid0** [comment]
This might be related to https://github.com/nextcloud/richdocuments/issues/1282

**Comment by kojid0** [comment]
Since https://github.com/nextcloud/richdocuments/issues/1282 is locked, I want to ask about the current state of the issue? It has been around for at least 1,5 years now... @juliushaertl

**Comment by jivanpal** [comment]
Experiencing this issue with a fresh native installation (not Dockerised, Snap, etc.) of Nextcloud 24.0.3 under Ubuntu 22.04, PHP-FPM 8.2.1, Nginx 1.18.0. Nothing interesting in any logs, but disabling `richdocuments` (version 6.1.1) and `richdocumentscode` (version 22.5.401) resolves the issue.

If a fresh installation of Nextcloud is done, enabling `richdocuments` but not enabling `richdocumentscode`, then there is no issue. However, after enabling `richdocumentscode`, both it and `richdocuments` must be disabled for the issue to go away.

**Comment by AJMitev** [comment]
I am experiencing the same thing. The issue began two days ago without any reason. I just waked up on 31st July and my server did not resolve any request until I disabled richdocuments and richdocumentscode_arm64. I am using  NC 24.0.4 with richdocuments v6.2.0 and richdocumentscode_arm64 v 22.5.502. installed on bare metal Raspberry PI 4B under Ubuntu 20.04.05

Disabling richdocuments and reboot the server resolved my issue no matter if richdocumentscode_arm64 is enabled or not. I hope somebody can give us some tip how to fix this situation.

**Comment by TobiGr** [comment]
I am facing the same problem since multiple NextCloud versions. When richdocuments / Nextcloud Office is enabled, the whole server needs ages to load anything and resolve requests. I am running my server on a Raspberry PI 4B with 4GB RAM with Debian bullseye and using the NectcloudPi image. I use the CODE ARM64 version (23.5.103), the problem existed with previous versions as well. The problem occurred about one year ago, the setup was working without any problems until that point.
 
<details><summary>Server Condig</summary>

## Server configuration detail

**Operating system:** Linux 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.39

**PHP version:** 8.0.29

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, fileinfo, mbstring, sockets, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, exif, FFI, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 26.0.3 - 26.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

[]
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.18.0
 - bruteforcesettings: 2.6.0
 - calendar: 4.4.3
 - checksum: 1.2.2
 - circles: 26.0.0
 - cloud_federation_api: 1.9.0
 - comments: 1.16.0
 - contacts: 5.3.2
 - contactsinteraction: 1.7.0
 - dav: 1.25.0
 - drawio: 2.1.1
 - federatedfilesharing: 1.16.0
 - federation: 1.16.0
 - files: 1.21.1
 - files_pdfviewer: 2.7.0
 - files_rightclick: 1.5.0
 - files_sharing: 1.18.0
 - files_trashbin: 1.16.0
 - files_versions: 1.19.1
 - fileslibreofficeedit: 1.1.0
 - firstrunwizard: 2.15.0
 - forms: 3.3.1
 - geoblocker: 0.5.11
 - groupfolders: 14.0.2
 - logreader: 2.11.0
 - lookup_server_connector: 1.14.0
 - nextcloud_announcements: 1.15.0
 - nextcloudpi: 0.0.1
 - notes: 4.8.0
 - notifications: 2.14.0
 - notify_push: 0.6.3
 - oauth2: 1.14.0
 - password_policy: 1.16.0
 - photos: 2.2.0
 - polls: 5.1.0
 - privacy: 1.10.0
 - provisioning_api: 1.16.0
 - recommendations: 1.5.0
 - related_resources: 1.1.0-alpha1
 - serverinfo: 1.16.0
 - settings: 1.8.0
 - sharebymail: 1.16.0
 - spreed: 16.0.4
 - support: 1.9.0
 - survey_client: 1.14.0
 - systemtags: 1.16.0
 - tasks: 0.15.0
 - text: 3.7.2
 - theming: 2.1.1
 - twofactor_backupcodes: 1.15.0
 - twofactor_totp: 8.0.0
 - updatenotification: 1.16.0
 - user_status: 1.6.0
 - viewer: 1.10.0
 - workflowengine: 2.8.0
Disabled:
 - admin_audit
 - apporder: 0.15.0
 - dashboard: 7.1.0
 - encryption: 2.9.0
 - extract: 1.3.5
 - files_external
 - previewgenerator
 - richdocuments: 8.0.2
 - richdocumentscode_arm64: 23.5.103
 - suspicious_login
 - transfer: 0.6.1
 - user_ldap
 - weather_status: 1.1.0

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "1": "***REMOVED SENSITIVE VALUE***",
        "0": "***REMOVED SENSITIVE VALUE***",
        "11": "***REMOVED SENSITIVE VALUE***",
        "3": "nextcloudpi",
        "22": "nextcloudpi",
        "14": "nextcloudpi",
        "": "nextcloudpi"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "26.0.3.2",
    "overwrite.cli.url": "https:\/\/nextcloudpi\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": "2",
    "log_type": "file",
    "maintenance": false,
    "theme": "",
    "htaccess.RewriteBase": "\/",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "default_phone_region": "DE",
    "overwriteprotocol": "https",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "integration_whiteboard"
    ],
    "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
    "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
    "data-fingerprint": "c6c53bd0ebb21ce00b5eda0812775909",
    "trashbin_retention_obligation": "disabled"
}
```
</details>

**Cron Configuration:** Array
(
    [backgroundjobs_mode] => cron
    [lastcron] => 1688417402
)


**External storages:** files_external is disabled

**Encryption:** no

**User-backends:** 
 * OC\User\Database


**Talk configuration:** 

STUN servers
 * no custom server configured

TURN servers
 * no custom server configured

Signaling servers (mode: default):
 * no custom server configured

</details>

**Comment by juliushaertl** [comment]
We have fixed this by no longer running requests that could timeout or be slower on every request with https://github.com/nextcloud/richdocuments/pull/3749.
