### ISSUE TITLE
Unable to see documents with collabora 21.11.0.3.1

### ISSUE THREAD

**Issue by larochef** [nextcloud/richdocuments#1889]
**Describe the bug**

After upgrading collabora to 21.11.0.3.1 (I'm using docker, it is currently the latest version), I cannot open my documents anymore, with a white page, and some JS stack trace:

Upgrading collabora hasn't been as straightforward as the other times, since the `loolwsd` files were somewhat renamed to `coolwsd`, I suspect that a few more things might have changed too.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - OS: archlinux
 - Browser firefox
 - Version latest
 - Device: -

## Server details

**Operating system**:
Archlinux

**Web server:**
latest docker image for nextcloud

**Database:**
mariadb

**PHP version:**

**Nextcloud version:**
22.2.3

**Version of the richdocuments app**
4.2.3

**Version of Collabora Online**
21.11.0.3.1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
trigger@https://**********/core/js/dist/main.js?v=11d43873-3:25:66171
trigger/<@https://**********/core/js/dist/main.js?v=11d43873-3:25:66457
each@https://**********/core/js/dist/main.js?v=11d43873-3:14:2654
each@https://**********/core/js/dist/main.js?v=11d43873-3:14:1326
trigger@https://**********/core/js/dist/main.js?v=11d43873-3:25:66432
o</</</e.fn[n]@https://**********/core/js/dist/main.js?v=11d43873-3:986:9051
showEditor@https://**********/custom_apps/richdocuments/js/richdocuments-document.js?v=11d43873-3:2:224618
showEditor/<@https://**********/custom_apps/richdocuments/js/richdocuments-document.js?v=11d43873-3:2:219772
```

</details>

**Comment by ccandreva** [comment]
I'm seeing a very similar issue with Collabore/code 21.11.0.3.1 , CODE 4.2.3

When I try to open a docuement I see a 404 error, apparently from this URL:

`https://collabora.mydomain.xx/browser/b5534c4/cool.html?WOPISrc=https%3A%2F%2Fnextcloud.mydomain.xx%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F122466_oci0kvic1pmf&title=[removed for privacy]
`
The issue seems to be the **https://collabora.mydomain.xx/browser** part, as **/browser/** is not mentioned in the documentation as a root to configure Apache's ProxyPass for in the docs:
https://nextcloud.com/collaboraonline/

Is this now required by the configuration ? I added rules for /browser/ and I see the splash as if it's trying to load, then get errors for a web socket **wss://collabora.candreva.us/cool/**

**Comment by ccandreva** [comment]
Updated proxy settings are available from the Collabora Online SDK docs:
https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html

Nextcloud documentation should be updated to match.

**Comment by larochef** [comment]
I have given it a try, but it doesn't change anything.
I also had no problem displaying the admin console with the parameters I had before.

The strange thing is that I don't see any network call to my collabora from my browser when I try to open the document. In the nextcloud logs, I do see the calls to rich document, but all calls succeed with a 200 status code

**Comment by larochef** [comment]
After some time searching, adding `--cap-add MKNOD` to my docker command line to start collabora fixed it.

Thx for the pointer to the doc, which had it ;)
