### ISSUE TITLE
error open "collabora"

### ISSUE THREAD

**Issue by prcant** [nextcloud/richdocuments#207]
Im click on the .doc file, the Nextcloud view the error:
"Il server non è stato in grado di completare la tua richiesta.
Se ciò si verifca nuovamente, invia i seguenti dettagli tecnici all'amministratore del server.
Ulteriori dettagli sono disponibili nel log del server.
Dettagli tecnici

Indirizzo remoto: 10.0.0.183
ID richiesta: WwKPK@MvXubtoGO9w2XCmgAAAAA
"
not have the solution this problem

**Comment by thebearon** [comment]
Does that only happen when opening DOC files (or one particular DOC file), or also with other formats? If it happens with all files, it is likely a server misconfiguration, likely Nextcloud can't verify the certificate set for Collabora Online.

Since no further details were given, and this is not a support forum, I'm closing the ticket.
