### ISSUE TITLE
Calc bottom bar is missing in some browsers

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#2082]
- Happens on Safari
- The bottom bar for switching spreadsheets is missing
- Seems to come from #toolbar-up having a fixed height set of 44px in branding

**Comment by manu-p** [comment]
Same on Brave and Firefox latest versions. Blocking since many ods use multiple tabs.

**Comment by manu-p** [comment]
It's the same in Writer and Impress. No bottom bar to select sheet, search, select language, etc. in calc
No bottom bar to seach, select language, zoom, etc. in writer and impress.

**Comment by dodedodo** [comment]
@manu-p I suspect you and julius are talking about 2 different bars. The bar that displays language, zoom, search etc can be enabled in 'View' -> 'Toggle Status Bar'.

The spreadshead worksheet-tabs work correctly by default for me in both firefox and chromium-based browsers (ff, edge, chromium, chrome-android). This is in docker collabora/code:21.11.2.2.1 + nextcloud:23.0.2 + richdocuments v5.0.2

**Comment by manu-p** [comment]
Thanks @dodedodo. Is the "View" menu you're talking about is new to richdocuments 5? (being on a production instance, I can't play to change version anytime, I rollbacked to 4.2.4 and there's no "View" menu).

I'm talking about these 2 lines in an ODS file (same for other filte types) you can see here: https://ibb.co/1bxVHs1

**Comment by manu-p** [comment]
On another instance, I can see the bottom line (Search... Sheet 1 of 3 etc.) is still not displayed in Nextcloud Office 5.0.3

**Comment by manu-p** [comment]
@dodedodo Could you please answer my question or, even better show where one is supposed to find the 'View' -> 'Toggle Status Bar'?

**Comment by dodedodo** [comment]
I'm sorry for the delay @manu-p. My UI might look and work a little different than yours. I've enabled the nootbookbar option on my collabora server. 

Here's a screenshot from my nextcloud collabora. It's in dutch, unfortunately, but the buttons should be in the same place. Clicking 'toggle status bar' toggles the bar highlighted at the bottom. The other bar containing the worksheet tabs is enabled by default, and cannot be toggled as far as I know. 
![image](https://user-images.githubusercontent.com/3252036/160258796-98b6a152-6bb3-49f8-bcda-f95af83944ef.png)

**Comment by manu-p** [comment]
Hi, here's what I get on our sides. I added the Help > About pop up for you to see the CODE version in case it's usefull.

![Capture d’écran de 2022-03-27 09-36-57](https://user-images.githubusercontent.com/14906222/160271822-84bab369-57eb-45f1-b470-1d5559b24cf4.png)

**Comment by manu-p** [comment]
@dodedodo could you please post the versions of CODE and NC Document you're using in your display?

**Comment by manu-p** [comment]
Hi,

> @dodedodo could you please post the versions of CODE and NC Document you're using in your display?

No answer... :-/

No way to know if this bug is being solved, and when when may expect to get a new version solving the issue.

Just keep sticking with Collabora online 4.2.4, at least everything's here with this version.

**Comment by manu-p** [comment]
And suddenly I feel less alone (although I already know I'm not)

**Comment by dodedodo** [comment]
Hey @manu-p, I'm sorry I couldn't get back to you sooner. Life gets in the way sometimes. 

The version numbers mentioned in my first comment are true for all my comments. Note that I'm not using the latest versions right now.
> ... docker collabora/code:21.11.2.2.1 + nextcloud:23.0.2 + richdocuments v5.0.2

I still feel like we're talking about 2 separate bugs in this issue. Maybe this should be tracked in 2 separate issues? I won't do that because the 2nd bug does not affect me.

1. The spreadsheet tab-bar does not show with notebookbaar-ui enabled in safari/epiphany.
2. The 'Toggle Status Bar' button does not show. (the status-bar is not the same thing as the tab-bar) 

I can reproduce bug 1 in epiphany with notebookbar enabled (but it does work fine with 'classic' UI)

I tested bug 2 again with different file formats (including .ods), in both classic UI and notebookbar, and with chromium and epiphany. Unfortunately, I still cannot reproduce bug 2. The 'Toggle Status Bar' button is always present for me. Regardless of document format or UI style.

**Comment by manu-p** [comment]
Hi, after struggling a bit with the nginx conf and the docker-compose.yml for collabora, due to some traps here and there, I finally managed to install the latest collabora docker image and the latest NC interface module and it solved it all together.

**Comment by juliushaertl** [comment]
Should be fixed with one of the recent collabora releases already.
