### ISSUE TITLE
Documentation issue on page for "Collabora Online - Built-In CODE Server": "Collabora Online" → "Nextcloud Office"

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/richdocuments#2083]
![grafik](https://user-images.githubusercontent.com/1151915/156882075-9af53274-2ae8-4c27-b34f-ca3a613e7986.png)

On the shown page for the Collabora Online - Built-In CODE Server, the text should be corrected from „Collabora Online“ to → "Nextcloud Office"

N.B.
Because I could not find the correct github repo for filing the present issue, I hope, that someone of you readers can help this report to find the correct repo.

**Comment by joshtrichards** [comment]
The correct repository for this is:

https://github.com/CollaboraOnline/richdocumentscode

I've gone ahead and proposed a PR over there to fix it:

https://github.com/CollaboraOnline/richdocumentscode/pull/250

It'll be up to them whether to accept it or not.

Since we can't do anything about this here I'm going to close.
