### ISSUE TITLE
Chinese characters do not show

### ISSUE THREAD

**Issue by dotKokott** [nextcloud/richdocuments#2138]
**Describe the bug**
Chinese characters cannot be viewed or entered in a .odt or .docx Nextcloud Office document.

**To Reproduce**
1. Create new document
2. Copy paste the following characters '漢字'
3. Observe that they only show up as squares.

**Expected behavior**
Characters should show

**Screenshots**

**Client details:**
 - OS: Windows and OSX
 - Browser brave
 - Version: latest
 - Device: Desktop and Macbook

## Server details

**Operating system**:
Ubuntu 20

**Web server:**
whatever is configured in nextcloud:latest

**Database:**
mariadb

**PHP version:**
whatever is configured in nextcloud:latest

**Nextcloud version:**
nextcloud:latest

**Version of the richdocuments app**
COOLWSD version:
21.11.2.4

**Version of Collabora Online**
21.06.20.1

**Comment by juliushaertl** [comment]
I cannot reproduce this here, since it seems you are using docker for the Nextcloud server, are you also using the collabora/code image? Could you check if updating to the latest one of that([21.11.3.6.1](https://hub.docker.com/layers/code/collabora/code/21.11.3.6.1/images/sha256-df95183aa36a08b0ddbfbe8488a964d38ff6c7de4befed511fb2ed2fbc0871d6?context=explore)) solves the issue?

**Comment by dotKokott** [comment]
Using the collabora/code:latest image and setting it up instead of the built-in CODE server of the nextcloud:latest worked! Characters are showing properly now (including a general speed improvement!)

Thank you!

**Comment by mixky234** [comment]
> Using the collabora/code:latest image and setting it up instead of the built-in CODE server of the nextcloud:latest worked! Characters are showing properly now (including a general speed improvement!)
> 
> Thank you!

Can you please describe how you make it work?
