### ISSUE TITLE
richdocuments appears not to start on new installation

### ISSUE THREAD

**Issue by crashbandicode** [nextcloud/richdocuments#2173]
**Describe the bug**
When starting with a fresh installation of richdocuments, it appears that the service isn't running causing creating new documents to fail

**To Reproduce**

1. Start with a fresh docker nextcloud installation
2. Install all recommended apps (which includes the collabora richdocuments app)
3. navigate to files
4. try and create a file
5. it will fail
6. do a `netstat -plunt` in the container and see it's not listening on `9983`
7. go to settings > administration > office, click "use your own server" then click "use built in code..." 
8. Navigate back to files
9. try and create a file and see it works
10. run `netstat -plunt` in the container again and see the port is listening

**Expected behavior**
You should be able to use nextcloud documents right after installing the built in code plugin

**Client details:**
 - OS: Ubuntu 21.10
 - Docker: Docker version 20.10.14, build a224086
 - Browser: Firefox
 - Version 99.01
 - Device: desktop

## Server details

**Operating system**: Ubuntu 21.10

**Web server:** built in apache

**Database:** postgres

**PHP version:** 8.0.17

**Nextcloud version:** 23.0.3

**Version of the richdocuments app** 5.0.3

**Version of Collabora Online** Built-in CODE Server 21.11.306

**Comment by KarelWintersky** [comment]
Same issue (Debian 11, PHP 7.4, nginx)

**Comment by Raudius** [comment]
Hi, thanks for the report.

I believe the issue is that the config value for the `wopi_url` is not set until you select it in the administration settings.

This app cannot be guessing when the built-in code is installed/enabled. So this issue is better suited for the [`richdocumentscode`](https://github.com/CollaboraOnline/richdocumentscode) repository, as they can make sure that the app config value is set.
 
Can you check if this is still an issue and raise it in the right repository?
