### ISSUE TITLE
Back Button is missing on iPad

### ISSUE THREAD

**Issue by Giusemx** [nextcloud/richdocuments#2639]
Again to reopen "Back Button is missing on iPad #2398",  the bug is actually not fixed.
It is not possible to leave documents after start editing it. The Nextcloud logo doesn't work, and the "X" is not there.
In Firefox on Desktop if simulate Tablets, the "X" is there. But if test on a Tablet, like iPad Air, Pro and an android Tablet, the issue is there. No way to leave the documents. Only can close Nextcloud completely and reopen it, but that is not nice...

In the closed post, i understand that the issue is fixed, but i can't confirm that.
Thanks for your time.

**Comment by thebearon** [comment]
It's probably helpful to add your Nextcloud and Nextcloud Office app version, and screenshots of what you see on your devices.

**Comment by Giusemx** [comment]
Nextcloud 25.0.1
Nextcloud Office 7.0.1
I don't have the tablets here right now. All looks the same like on firefox when simulate the tablets resolutions, but the "X" button is missing.

**Comment by joshtrichards** [comment]
What version of Collabora Online/CODE? This may not be just a Nextcloud Office integration app (richdocuments) matter. 

Is this different from #3024?

**Comment by juliushaertl** [comment]
We always show the closebutton since https://github.com/nextcloud/richdocuments/pull/2451

However it might be related to Collabora Online that didn't have proper handling of the top bar for smaller screens whis should have been addressed with https://github.com/CollaboraOnline/online/pull/7327.

Please try the latest release and if there is still an issue you see, please share a screenshot.
