### ISSUE TITLE
Horizontal Scrolling not possible IOS Devices

### ISSUE THREAD

**Issue by theDyingMountain** [nextcloud/richdocuments#266]
On IOS Devices, i can't scroll any office document horizontally.

### Steps to reproduce
1. Open Collabora App in nextloud
2. Open Office Document (i.e. .odt, .doc...)
3. Scroll horizontally to look over document

### Expected behaviour
The screen is scrolling, so i can view the full document

### Actual behaviour
No scrolling appears

**Comment by juliushaertl** [comment]
Thanks for your bug report. This issue tracker is only targeting the collabora integration inside Nextcloud. There actually have been quite some improvements in the last Collabora release, so I recommend you to try with an update version.

Your issue is actually related to Collabora/LibreOffice Online, so please head over to https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online for reporting.
