### ISSUE TITLE
Add right click menu option to open document

### ISSUE THREAD

**Issue by kelvinhammond** [nextcloud/richdocuments#2668]
**Is your feature request related to a problem? Please describe.**
When I click on a file it always tries to download the file and will not open it in CODE and I have no way of knowing what the issue is or how to force it to open with CODE.

**Describe the solution you'd like**
In Nextcloud for web when right clicking on a document it should be possible to select open with CODE (or whatever you want to call it). 

**Describe alternatives you've considered**
There are no alternative ways to open files with the builtin code server at the moment

**Additional context**
No

**Comment by joshtrichards** [comment]
> When I click on a file it always tries to download the file and will not open it in CODE and I have no way of knowing what the issue is or how to force it to open with CODE.

What CODE deployment do you have in-place? (This app here only provides the integration - you still need to be running a dedicated CODE server/instance and/or install the separate *Collabora Online - Built-in CODE Server* aka `richdocumentscode` app).

While your request is for an enhancement, it sounds like the real issue is that your setup isn't functioning. So I'm afraid trying to force CODE to open in some other way isn't viable. If CODE was installed/functioning properly than it would open automatically for these files.


If still stuck, please post your configuration details over at the Nextcloud Help Forum - https://help.nextcloud.com - to get some guidance or troubleshooting ideas.
