### ISSUE TITLE
Blank Screen - no document opens (Using Nginx & Docker)

### ISSUE THREAD

**Issue by mistergibson** [nextcloud/richdocuments#287]
### Steps to reproduce
1. Configure Nginx reverse proxy (see attached config file for nextcloud & collabora)
2. Start nginx
3. Open Test.odt file in nextcloud

### Expected behaviour
Tell us what should happen
It should present me with the Collabora environment and tools with the document open.
### Actual behaviour
Tab is blank -- nothing, nada. It still bears the nextcloud menu and file tab -- but collabora never cranks up and displays anything.

### Server configuration

Ubuntu 18.04 Server

Nginx

MySQL

PHP7.1-fpm

14.0.3

Fresh Install

Nextcloud ... latest.zip

```
No errors have been found.
```

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - drawio: 0.9.1
  - event_update_notification: 0.3.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_mindmap: 0.0.7
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mindmaps: 0.1.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - polls: 0.8.3
  - provisioning_api: 1.4.0
  - richdocuments: 3.0.1
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'octj2llmttxs',
  'passwordsalt' => '<redacted>',
  'secret' => '<redacted>',
  'trusted_domains' => 
  array (
    0 => 'nexus',
    1 => '<redacted>',
    2 => 'localhost',
  ),
  'datadirectory' => '/var/lib/nextcloud',
  'dbtype' => 'mysql',
  'version' => '14.0.3.0',
  'overwrite.cli.url' => '<redacted>',
  'dbname' => 'nextcloud',
  'dbhost' => '<redacted>',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '<redacted>',
  'dbpassword' => '<redacted>',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 62.0.3 (64bit)

**Operating system:**
Linux Mint (client side) 19 Tara / Ubuntu Server 18.04 (server side)

#### Web server error log
2018/10/23 19:07:11 [error] 8179#8179: *62 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, 
client: 97.120.38.13, server: cdc.csproject.org, request: "GET /hosting/discovery HTTP/1.1", upstream: "https://127.0.0.1:9980/hosting/discovery", hos
t: "cdc.csproject.org"
2018/10/23 19:07:11 [error] 8179#8179: *62 connect() failed (111: Connection refused) while connecting to upstream, client: 97.120.38.13, server: cdc.
csproject.org, request: "GET /hosting/discovery HTTP/1.1", upstream: "https://[::1]:9980/hosting/discovery", host: "cdc.csproject.org"
2018/10/23 19:07:11 [error] 8179#8179: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class GuzzleHttp\Exception\RequestExc
eption, because the name is already in use in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php on line 0" while readin
g response header from upstream, client: 97.120.38.13, server: cdc.csproject.org, request: "GET /apps/richdocuments/index?fileId=596&requesttoken=c7nU
Cw9CruUJoiK6TwaJmAtnUiimnSaFG1hMjwJM3Fc%3D%3AQfe1bm4F69JFyw3XKTX%2FoWIAYX%2BRzm7TXWEW1zsjqz4%3D HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-f
pm.sock:", host: "cdc.csproject.org"

#### Nextcloud log (data/nextcloud.log)
{"reqId":"YYLtgwnLCxgwddJrDObx","level":3,"time":"2018-10-24T02:14:59+00:00","remoteAddr":"97.120.38.13","user":"mistergibson","app":"richdocuments","
method":"GET","url":"\/apps\/richdocuments\/index?fileId=596&requesttoken=QnrtsnNZJtmPGxArfF2LZj%2FvwHYhnjL35qFBXFaEtNI%3D%3AcDSM1xIeY%2B7Dcj9GGm79X1a
I8yEWzXqhoJgbBG%2Frw7s%3D","message":{"Exception":"GuzzleHttp\\Exception\\ServerException","Message":"Server error: `GET https:\/\/cdc.csproject.org\/
hosting\/discovery` resulted in a `502 Bad Gateway` response:\n<html>\r\n<head><title>502 Bad Gateway<\/title><\/head>\r\n<body bgcolor=\"white\">\r\n
<center><h1>502 Bad Gateway<\/h1><\/center>\r\n (truncated...)\n","Code":502,"Trace":[{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/sr
c\/Middleware.php","line":65,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":[{"__class__":"GuzzleHttp\\Psr7\
\Request"},"*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":203,"func
tion":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/next
cloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":156,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::","args"
:[1,"*** sensitive parameter replaced ***",[{"__class__":"GuzzleHttp\\Promise\\Promise"},{"__class__":"Closure"},null]]},{"file":"\/var\/www\/nextclou
d\/3rdparty\/guzzlehttp\/promises\/src\/TaskQueue.php","line":47,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","t
ype":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":2
46,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->","args":[true]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises
\/src\/Promise.php","line":223,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\
/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":267,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]}
,{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":225,"function":"invokeWaitList","class":"GuzzleHttp\\Promise
\\Promise","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":62,"function":"waitIfPendin
g","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php","line"
:131,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Http\/Client\/Clien
t.php","line":161,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["get","https:\/\/cdc.csproject.org\/hosting\/discovery",{"veri
fy":"\/var\/lib\/nextcloud\/files_external\/rootcerts.crt","synchronous":true}]},{"file":"\/var\/www\/nextcloud\/apps\/richdocuments\/lib\/WOPI\/Disco
veryManager.php","line":84,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https:\/\/cdc.csproject.org\/hosting\/discovery"]}
,{"file":"\/var\/www\/nextcloud\/apps\/richdocuments\/lib\/WOPI\/Parser.php","line":41,"function":"get","class":"OCA\\Richdocuments\\WOPI\\DiscoveryMa
nager","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/richdocuments\/lib\/TokenManager.php","line":148,"function":"getUrlSrc","class":"O
CA\\Richdocuments\\WOPI\\Parser","type":"->","args":["application\/vnd.oasis.opendocument.text"]},{"file":"\/var\/www\/nextcloud\/apps\/richdocuments\
/lib\/Controller\/DocumentController.php","line":179,"function":"getToken","class":"OCA\\Richdocuments\\TokenManager","type":"->","args":["*** sensiti
ve parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"index","class":
"OCA\\Richdocuments\\Controller\\DocumentController","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\
/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args"
:[{"__class__":"OCA\\Richdocuments\\Controller\\DocumentController"},"index"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","l
ine":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\Document
Controller"},"index"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class
":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\DocumentController","index",{"__class__":"OC\\AppFramework\\DependencyI
njection\\DIContainer"},{"_route":"richdocuments.document.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","ty
pe":"->","args":[{"_route":"richdocuments.document.index"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"c
all_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"richdocuments.document.index"}]},{"file":"\/var\/www\/
nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/richdocuments\/index"]},{"file":"\/va
r\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/3rdparty\/guzzl
ehttp\/guzzle\/src\/Exception\/RequestException.php","Line":113,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) G
ecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"YYLtgwnLCxgwddJrDObx","level":3,"time":"2018-10-24T02:14:59+00:00","remoteAddr":"97.120.38.13","user":"mistergibson","app":"PHP","method":"G
ET","url":"\/apps\/richdocuments\/index?fileId=596&requesttoken=QnrtsnNZJtmPGxArfF2LZj%2FvwHYhnjL35qFBXFaEtNI%3D%3AcDSM1xIeY%2B7Dcj9GGm79X1aI8yEWzXqho
JgbBG%2Frw7s%3D","message":"Cannot declare class GuzzleHttp\\Exception\\RequestException, because the name is already in use at \/var\/www\/nextcloud\
/3rdparty\/guzzlehttp\/guzzle\/src\/Exception\/RequestException.php#0","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko\/20100101 
Firefox\/62.0","version":"14.0.3.0"}

**Comment by blackisle51** [comment]
I have also encountered this issue but with Apache proxy. Updated from V13 with everything functioning to 14.03. 
Blank page, no Collabora editor window. 

Log:


Error | PHP | Cannot  declare class GuzzleHttp\Handler\CurlFactory, because the name is  already in use at  /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php#16 | 2018-10-29T20:38:27+0000
-- | -- | -- | --
Error | richdocuments | GuzzleHttp\Exception\ConnectException: cURL  error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3  alert handshake failure (see  http://curl.haxx.se/libcurl/c/libcurl-errors.html)/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 150: GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\H ... l}, { errno: 35, ... 6})/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 103: GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php - line 43: GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 28: GuzzleHttp\Handler\CurlHandler->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 51: GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php - line 37: GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 30: GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 70: GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 59: GuzzleHttp\RedirectMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php - line 67: GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 277: GuzzleHttp\HandlerStack->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->transfer("*** sensiti ... *", "*** sensiti ... *")/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131: GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, { verify: "/ ... }})/var/www/nextcloud/lib/private/Http/Client/Client.php - line 161: GuzzleHttp\Client->request("get", "https://off ... y", { verify: "/ ... e})/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get("https://off ... y")/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 148: OCA\Richdocuments\WOPI\Parser->getUrlSrc("application ... t")/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 179: OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Richdocuments\Controller\DocumentController->index("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocu ... {}, "index")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocu ... {}, "index")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Richdo ... r", "index", OC\AppFramew ... {}, { _route: "r ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "r ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "r ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/richdocuments/index")/var/www/nextcloud/index.php - line 42: OC::handleRequest()

**Comment by blackisle51** [comment]
Found the issue, looks like curl doesn't like SSL2/3 anymore. Changed my .conf to "SSLProtocol -all +TLSv1.2" and everything now working :)

**Comment by monreal** [comment]
@mistergibson: do you also get "502 Bad Gateway" if you wait long enough?

**Comment by mistergibson** [comment]
@blackisle51 --> nginx.conf: ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
Where/What file did you change to add TLSv1.2?

@monreal --> No, no 'Bad Gateway', just sits there blank forever.

**Comment by mistergibson** [comment]
Update: I updated collabora instance on docker and that solved the 'bad gateway' issue. However, **all I get now is a spinning circle** --> the document editor never loads.

**Comment by mistergibson** [comment]
Update TWO: Switched to NON-Docker install of loolwsd, and configured it to use my letsencrypt cert and key. All is good on hosting/discovery, and I can get an empty editor to launch in my browser (with no file or content associated) following one of the WOPI declared links. However, **All I still get is a spinning circle** in my browser when I attempt to open a file. I'm convinced at this point it is in the Collabora Online app on the nextcloud side of things. It just cannot get the file content to the tool to open. If anyone has any ideas I'd appreciate the input.

**Comment by juliushaertl** [comment]
> Firefox can’t establish a connection to the server at wss://cdc.csproject.org/lool/https%3A%2F%2F[REDACTED]%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F283_octj2llmttxs%3Faccess_token%3DgWzpwWVsLZdTxprmwLyt08IF3rtsoUiH%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2F[REDACTED]%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F283_octj2llmttxs&compat=/ws.

This looks like a configuration problem with your webserver. Please check the forums for further help on that: https://help.nextcloud.com

**Comment by mistergibson** [comment]
um, NO --> AS I SAID: I can get the WOPI data, AND I can get the editor to load with a WOPI provided link (but no way to get the data file into the editor). So I am able to communicate with loolwsd. My nginx server configuration is right out of the book - otherwise I'd not get WOPI and the editor to open at all. I feel you closed this issue prematurely.

**Comment by juliushaertl** [comment]
> Firefox can’t establish a connection to the server at wss://cdc.csproject.org/lool/https%3A%2F%2F[REDACTED]%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F283_octj2llmttxs%3Faccess_token%3DgWzpwWVsLZdTxprmwLyt08IF3rtsoUiH%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2F[REDACTED]%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F283_octj2llmttxs&compat=/ws.

As the error states, the browser cannot establish the websocket connection to the collabora server, so please check your webserver configuration in that regards.

**Comment by carlox97** [comment]
> > Firefox can’t establish a connection to the server at wss://cdc.csproject.org/lool/https%3A%2F%2F[REDACTED]%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F283_octj2llmttxs%3Faccess_token%3DgWzpwWVsLZdTxprmwLyt08IF3rtsoUiH%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2F[REDACTED]%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F283_octj2llmttxs&compat=/ws.
> 
> As the error states, the browser cannot establish the websocket connection to the collabora server, so please check your webserver configuration in that regards.

I'm having his same problem. If i access nextcloud via its local IP, collabora works perfectly, but on the SSL secured domain, I get the blank page. If it's a websocket problem how can i fix it in the nextcloud reverse proxy entry?
