### ISSUE TITLE
 8.1.0: Close button is mission on small devices

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#3024]
![grafik](https://github.com/nextcloud/richdocuments/assets/24530680/8e92181f-736c-4e69-91b9-824b6bdffb24)
Tested in Firefox and Brave

**To Reproduce**
1. open office on a small screen or resize the window

With 8.0.2 its not an issue, only with 8.1.0

**Expected behavior**
The X button should be visible

**Workaround**
Resize the browser to 80% eg

**Client details:**
COOLWSD Version: 23.05.0.5 

Maybe similar to #2639

**Comment by SystemKeeper** [comment]
The close button is pushed out to the right when the screen gets smaller:
<img width="499" alt="image" src="https://github.com/nextcloud/richdocuments/assets/1580193/cc4cb01a-1780-4ff6-b9df-8c15e629cc73">
<img width="368" alt="image" src="https://github.com/nextcloud/richdocuments/assets/1580193/e87da829-df0d-4c90-afc7-1024ae722dba">

until it's not visible anymore.

Tried to change it via customcss like this

```
.hasnotebookbar #closebuttonwrapper {
  position: absolute;
  display: block;
  right: 0;
}

.hasnotebookbar #closebuttonwrapper:not(:hover) {
  background: var(--color-main-background);
}
```

But this does not work, because it's displayed inside a iframe.

I am wondering if the code at

https://github.com/nextcloud/richdocuments/blob/266f35331a732505879e86795fcfa01e12ab85f7/css/document.scss#L104-L112

had a similar intention back then?

**Comment by juliushaertl** [comment]
This has been fixed upstream in https://github.com/CollaboraOnline/online

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/richdocuments/blob/266f35331a732505879e86795fcfa01e12ab85f7/css/document.scss#L104-L112 could actually need some cleanup, this was from earlier times when the close button was rendered on the nextcloud side still.
