### ISSUE TITLE
Toggle grid view button from NC15 is visible on Collabora's toolbar

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#317]
Toggle grid view button is visible over the Collabora Online iframe area.
Nextcloud 15 RC1
![image](https://user-images.githubusercontent.com/290614/49165922-9942b400-f332-11e8-9635-7d1dd41c5fc0.png)

**Comment by tomastd** [comment]
The issue still there on 15RC2

<img width="200" alt="captura de pantalla 2018-12-04 a las 22 17 40" src="https://user-images.githubusercontent.com/25134714/49473578-b7b51d80-f812-11e8-89b9-1d73c9bd9dde.png">

**Comment by timmersr** [comment]
RC3: 
![3](https://user-images.githubusercontent.com/31093459/49644525-ee5c8500-fa18-11e8-9818-5510cf66661e.png)

**Comment by timmersr** [comment]
This issue still exists in Nextcloud 15.0.0
![5](https://user-images.githubusercontent.com/31093459/49737054-13a4f980-fc8c-11e8-987f-69d8c3148d57.png)

**Comment by rullzer** [comment]
I'll release a new richdocuments this evneing that has a fix.

**Comment by rev138** [comment]
@rullzer As of 3.0.5 this is not fixed.

**Comment by elpraga** [comment]
@rullzer I confirm, not fixed in the 3.0.5

Moreover, on the mobile devices, it blocks the whole menu, rendering __the entire Collabora menu inaccessible__. Collabora has recently revamped the icons shown on mobile devices, and made it simple, with __many basic features__ accessible only via the menu. With the menu inaccessible, many of these basic features are not accessible at all.

**Comment by rullzer** [comment]
I could not release from the train. But 3.0.6 is live and has it fixed.

**Comment by rev138** [comment]
Confirmed. Thanks!
