### ISSUE TITLE
Share sidebar opens behind Office window after NC27.1.x update

### ISSUE THREAD

**Issue by sebastiaanveld** [nextcloud/richdocuments#3199]
**Describe the bug**
Share sidebar opens behind Office window after NC27.1.x update. Since updating to 27.1.0 and also with 27.1.1 the Share sidebar opens behind the Office window. Also the Office Windows top is slightly lower then with NC 26.x and before. Same issue with Firefox or Edge.

**To Reproduce**
1. Update NC27.0.x to 27.1.0 or 27.1.1
2. Click on a document to open with CODE. Visually the CODE window is opened visually lower vs the Nextcloud visual window
3. Click the Share button on the right to screen. The Windows is opened behind the Office visual window, which makes it unusable.

**Expected behavior**
Normally the Office windows gets smaller and the share screen is opened on the right side.

**Screenshots**
The Office Windows is opened lower vs the Nextcloud screen in the background:

![image](https://github.com/nextcloud/richdocuments/assets/37268999/ec7cf6bb-8674-4dfb-a93b-4f5594ec356a)

The Sharing sidebar is opened in the background instead of in the foreground:

![image](https://github.com/nextcloud/richdocuments/assets/37268999/f84d7e1b-105e-4799-a757-fc1a995b4ff4)

**Client details:**
 - OS: Windows 11, latest patches, Dutch
 - Browser Firefox 117.0.1 (x64, Dutch), 
 - Browser Edge 117.0.2045.41 (Officiële build) (64-bits)

## Server details

**Operating system**: Ubuntu 22.04.3 LTS (Hanson IT 'appliance')

**Web server:** Apache 

**Database:** PostgreSQL

**PHP version:** 8.1

**Nextcloud version:** 27.1.0 or 27.1.1

**Version of the richdocuments app** Nextcloud Office 8.2.0

**Version of Collabora Online** (external server, Docker)

COOLWSD version: 23.05.4.2 (git hash: 0b27e85 (E))
LOKit version: Collabora Office 23.05.4.2 (git hash: 78039c5)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: fdef652b

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Karamelmar** [comment]
i can confirm this behavior, which also results in a not usable "Status Bar", unless using Nextcloud Office in its Fullscreen Mode.
Made two screenshots in dark mode since it better shows the problem.

One quiet interesting fact to add:
i asked people here on the department to report on this issue... 
3 out of 12 that reported back, said they do NOT have this issue, 9 did.
All people that did not have this problem are on Laptops with resolutions at about FullHD.

![Screenshot from 2023-09-26 16-34-09](https://github.com/nextcloud/richdocuments/assets/44431078/e6df8b0f-d005-4e1c-bc1d-dd94bdc87fae)
![Screenshot from 2023-09-26 16-34-26](https://github.com/nextcloud/richdocuments/assets/44431078/5d5775c4-725a-432c-948a-1675c2636cb5)

**Comment by sebastiaanveld** [comment]
I found the "CADViewer" App to be the source of this issue. I had this enabled for some recent testing and one I disabled it (as part of disabling app one by one) the problem was gone.

**Comment by Karamelmar** [comment]
I can confirm this, had "CADViewer" activated aswell. After i disable it, the issue was gone.
Thank you! And i will report this issue on CADViewer!

**Comment by sebastiaanveld** [comment]
I'll close this issue as it seems related to the CADViewer App.
