### ISSUE TITLE
WOPI Allow list not recogonize X-Forwarded-For

### ISSUE THREAD

**Issue by chunlinyao** [nextcloud/richdocuments#3212]
My nextcloud behind reverse proxy. Collabora access nextcloud through the reverse proxy.
I want to config WOPI Allow list, It seems when check against allow list, nextcloud only check the remote address instead of the real client IP in X-Forwarded-For header.

**Expected behavior**
WOPI Allow list check against real client ip.

**Nextcloud version:**
27.1.1.

**Version of the richdocuments app**
8.2.0

**Version of Collabora Online**
21.06.20.1

**Comment by juliushaertl** [comment]
The header should definitely been taken into account depending on the Nextcloud configuration

https://github.com/nextcloud/richdocuments/blob/9ebdab305dea8bbd909cf66d4d4b92a054c2cdf5/lib/Middleware/WOPIMiddleware.php#L110
https://github.com/nextcloud/server/blob/e7cc7653b885c49b1b3f0a78f91ea05a53e102d8/lib/private/AppFramework/Http/Request.php#L596

You could try to set your log level to info and see which ip gets logged. Otherwise it might be needed to configure the proxy as `trusted_proxies` in your config.php

**Comment by chunlinyao** [comment]
Sorry, It was something wrong in my nginx config file.
