### ISSUE TITLE
WASM headers for online

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#3258]
As asked for by @mmeeks we would need to have `wasm-unsafe-eval` CSP headers set for WASM experiments currently taking place.

I checked back and we have a partly mechanism available to set those by https://github.com/nextcloud/server/pull/38082 this is however not used yet by Nextcloud Talk, as there the wasm is running in a service worker which doesn't require this.

We should be able to add those headers of course, just some additional questions:

@mmeeks To you have a need to run the online wasm in the main thread? As far as I understood this could have a significant impact on browser responsiveness.

**Comment by mmeeks** [comment]
Nope - we should run our WASM off the main thread, and do load, rendering etc. in the background; while continuing to render the UI in the main-thread with the same front-end code as now.

**Comment by juliushaertl** [comment]
In that case the header should not be needed as far as @danxuliu told me

**Comment by mmeeks** [comment]
Hmm - ok ? it seems that we need the parent frame of our iframe to have this @Ashod can you provide more details; quite possibly I've mistaken what's up here I think. Quite possibly our startup WASM runs in the main thread initially (not sure).

**Comment by Ashod** [comment]
I believe we need these two headers when serving the parent:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

Also had to add script-src unsafe-eval to the CSP header of our frame/js/wasm serving, but we will find out if that is required when we load with the above headers as the missing unsafe-eval was mentioned in the error message.

**Comment by juliushaertl** [comment]
unsafe-eval would be quite an impactful change security wise.

For the others I pushed a quick PR to https://github.com/nextcloud/richdocuments/pull/3260 which should achieve setting those headers for Nextcloud. However we should of course get more clarify about which headers to add in the end, why and its implications.

**Comment by mmeeks** [comment]
unsafe-eval sounds bad; but I think we can do that with wasm-eval in future :-) thanks Julius.

**Comment by Ashod** [comment]
> For the others I pushed a quick PR to #3260 which should achieve setting those headers for Nextcloud. However we should of course get more clarify about which headers to add in the end, why and its implications.

@juliushaertl, I'd like to run some tests locally. Any chance to get the draft PR polished so I can build locally and test? 
Thank in advance!

**Comment by juliushaertl** [comment]
@Ashod Pushed and should be testable with that now.

Reference for what it currently set currently set:
<img width="649" alt="Screenshot 2023-11-16 at 09 15 20" src="https://github.com/nextcloud/richdocuments/assets/3404133/29c71b3c-5baa-4875-82a3-61c35e6f76b7">

**Comment by Ashod** [comment]
Thanks @juliushaertl. The PR branch being out-of-date shouldn't be an issue?

@caolanm, does #3260 work for you? Are you able to apply it and build?

**Comment by juliushaertl** [comment]
Seems this was caused by those two headers: https://github.com/nextcloud/richdocuments/issues/3258#issuecomment-1781169694

I pushed a fix up to the PR.

**Comment by droogi** [comment]
It seems that these two headers block maps and memories to load tiles and thumbnails/pictures
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

**Comment by MichaIng** [comment]
Yeah, isn't it possible to achieve everything via CSP for the very individual pages of the Nextcloud Office app that require it, instead of globally for all Nextcloud?

While it breaks other apps, the only workaround seems to be to set `Cross-Origin-Embedder-Policy: credentialless`, which seems to imply things we do not want: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#credentialless
Also `credentialless` as well as `Cross-Origin-Opener-Policy` in general seem to not be supported by all browsers:
- https://caniuse.com/?search=Cross-Origin-Opener-Policy
- https://caniuse.com/?search=Cross-Origin-Embedder-Policy%3A%20credentialless

Hmm, only CSP option seems to be `wasm-unsafe-eval`: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution

@droogi could you open a new issue here about this? Actually not good to discuss in a closed one.
