### ISSUE TITLE
My CollaboraOnline don't work Online but work on localhost (with Firewall)

### ISSUE THREAD

**Issue by seint-aoc** [nextcloud/richdocuments#3574]
Hello,

I installed Nextcloud on my server hosted in the cloud, I saw the need to install Collabora Office and it asked me for an integrated CODE Server, I carried out the installation by default and in the Nextcloud Office section I selected the option to use CODE (Collabora Online Development Edition) but When I try to open a Spreadsheet type document it does not work from the WEB (It has a certificate and via WEB it works via HTTPS), however if I open it from the server via localhost it works and opens the spreadsheet.

I have Firewall on the server.
If i put the server on other public IP with no firewall is working (but the web is HTTP).

On localhost:
![image](https://github.com/nextcloud/richdocuments/assets/164916464/30789780-faa2-4ff8-80f5-414d59ad15d1)

On WEB via HTTPS:
![image](https://github.com/nextcloud/richdocuments/assets/164916464/29615e3a-59a3-4361-b395-f58d9b499c4b)

Any ideas?

**Comment by joshtrichards** [comment]
Given your description and what lead up to this situation, this sounds like a configuration or general troubleshooting matter rather than a bug. This channel is only for bug reporting. For assistance I suggest you post your situation on the Community Help Forum (https://help.nextcloud.com). 

Also, in the future, if you do report a bug, please do not bypass the reporting template. It asks for very specific information that we need in order to efficiently help you and others out. :)
