### ISSUE TITLE
Cannot open documents: "Document loading failed"

### ISSUE THREAD

**Issue by DaanSelen** [nextcloud/richdocuments#3906]
**Describe the bug**
After working fine for a long time, it suddenly does not work anymore with this screenshot after a short while of waiting:
![image](https://github.com/user-attachments/assets/0f8cc6c0-e039-49bb-b18f-6101beb28282)
I repulled the latest images for both nextcloud and collabora/code. But still this issue persists.

**To Reproduce**
Unknown

**Expected behavior**
Documents to open and function normally.

**Screenshots**
```
frk-00028-00028 2024-08-14 15:23:35.982168 +0200 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:555
wsd-00001-00102 2024-08-14 15:25:44.351204 +0200 [ docbroker_008 ] ERR  Doc [https%3A%2F%2Fcloud.nerthus.nl%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F43846_ocem17pa817x] is taking too long to load. Will kill process [89]. per_document.limit_load_secs set to 100 secs.| wsd/DocumentBroker.cpp:415
wsd-00001-00102 2024-08-14 15:25:44.363909 +0200 [ docbroker_008 ] ERR  #57: Read failed, have 0 buffered bytes (ECONNRESET: Connection reset by peer)| net/Socket.hpp:1149
wsd-00001-00102 2024-08-14 15:25:44.363988 +0200 [ docbroker_008 ] WRN  #57: Unassociated Kit (89) disconnected unexpectedly| wsd/COOLWSD.cpp:3699
wsd-00001-00102 2024-08-14 15:25:44.363999 +0200 [ docbroker_008 ] WRN  #57: Unknown Kit process closed with pid -1| wsd/COOLWSD.cpp:3706
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
```
![image](https://github.com/user-attachments/assets/7c547fb0-fe6c-4046-a67f-5386091254df)

The admin panel is also reachable fine, and the nextcloud instance can also reach collabora with the OK.

```
root@nextcloud-deploy-nextcloud-54dc8857dd-7wbd8:/config/www/nextcloud/apps# curl -L collabora.domain.com
OK
```

**Client details:**
 - OS: Windows
 - Browser Brave
 - Version: v1.68.137
 - Device: Desktop Computer

## Server details

**Operating system**:
Kubernetes on Linux
**Web server:**
NGINX
**Database:**
Postgresql
**PHP version:**
Latest?
**Nextcloud version:**
![image](https://github.com/user-attachments/assets/6b8eb2a3-cbfe-4516-986b-b24b7d8a9b2e)

**Version of the richdocuments app**
8.4.4
**Version of Collabora Online**
![image](https://github.com/user-attachments/assets/325f9412-da08-4fad-a4b0-013b74c5cfd6)

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "installed_version": "8.4.4",
            "enabled": "yes",
            "types": "prevent_group_restriction",
            "disable_certificate_verification": "",
            "wopi_allowlist": "0.0.0.0\/0",
            "wopi_url": "https:\/\/collabora.domain.com",
            "public_wopi_url": "https:\/\/collabora.domain.com"
        }
    }
}
```

#### Nextcloud log (data/nextcloud.log)
```
No new log entries on trying to reproduce
```

**Comment by DaanSelen** [comment]
To add to this, I tried another instance that is connected to the same collabora instance but runs on the same docker daemon as collabora itself, and it receives the same issue.

**Comment by joshtrichards** [comment]
The error suggests that your Collabora container isn't able to reach the Nextcloud one:

`ERR  Doc [https%3A%2F%2Fcloud.nerthus.nl%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F43846_ocem17pa817x] is taking too long to load`

So try the curl tests from that container and using the NC URL.

**Comment by DaanSelen** [comment]
> The error suggests that your Collabora container isn't able to reach the Nextcloud one:
> 
> `ERR Doc [https%3A%2F%2Fcloud.nerthus.nl%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F43846_ocem17pa817x] is taking too long to load`
> 
> So try the curl tests from that container and using the NC URL.

Thanks for the feedback, for now this is the response when curling the Nextcloud instance:

```
cool@af82fcc6eb8d:/$ curl cloud.nerthus.nl
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
cool@af82fcc6eb8d:/$ curl cloud.nerthus.nl -L
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" translate="no">
<head data-requesttoken="LopOxP60M0yBQYqL2FNzfNrlxhD6CQTMpVVifvVWuzs=:Z8YUiajDcCTYC8CyoColMq/dhHjPQjGblRcuR5cM3W8=">
<meta charset="utf-8">
<title>
                        Login – Nerthus Cloud           </title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
<meta name="apple-itunes-app" content="app-id=1125420102">
<meta name="theme-color" content="#8855a8">
<link rel="icon" href="/apps/theming/favicon?v=fe5dbbce">
<link rel="apple-touch-icon" href="/apps/theming/icon?v=fe5dbbce">
<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#8855a8">
<link rel="manifest" href="/apps/theming/manifest?v=fe5dbbce" crossorigin="use-credentials">
<link rel="stylesheet" href="/core/css/server.css?v=cc80af1d-8">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=0d6d4ea2-8">
<link rel="stylesheet" href="/core/
...
```

**Comment by gpolydoros** [comment]
I have the same problem. 

Both Nextcloud and Collabora are running as Docker containers, are accessible from the outside via NPM with valid certs etc. WOPI settings are also configured correctly. I really haven't changed anything at all and it used to work just fine for a long time until recently.

Don't know if it's because of the last update of Nextcloud Office or the latest upgrade to Nextcloud 29.0.5, but now I get the same error as reported by Daan.

**Comment by DaanSelen** [comment]
Issue is still present with version 8.4.5.

**Comment by gpolydoros** [comment]
For me as well, just tried 8.4.5 and the problem still exists.

**Comment by Lennyz1988** [comment]
Same issue here. Timeout and getting an error about Content-Security-Policy. (frame-ancestors) op <unknown> blocked, because it's in error with the following instruction: ‘frame-ancestors 'self'’

**Comment by DaanSelen** [comment]
> Same issue here. Timeout and getting an error about Content-Security-Policy. (frame-ancestors) op blocked, because it's in error with the following instruction: ‘frame-ancestors 'self'’

Can you post the log?

**Comment by DaanSelen** [comment]
@gpolydoros I do not know if it is the same issue, we see some kind of timeout, which I do not see in your error log. But welcome.

**Comment by Lennyz1988** [comment]
Setup: 

Nextcloud docker running behind Nginx reverse proxy.
Collabora office docker running behind Nginx reverse proxy. 

Both containers can talk to each other. 

No error logs in Collabora docker container. 

Chrome / Firefox log when opening a file:

ConsoleLogger.js:74 [ERROR] text: Unexpected Error "Failed to apply steps. Retry!" Object
value @ ConsoleLogger.js:74
viewer-main.mjs?v=b5455272-0:44 [INFO] viewer: Opening viewer for file  Object
Refused to frame 'https://office.mydomain.nl/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
NcButton.mjs:175 You need to fill either the text or the ariaLabel props in the button component. Object o
render @ NcButton.mjs:175
NcButton.mjs:175 You need to fill either the text or the ariaLabel props in the button component. Object o
render @ NcButton.mjs:175
2035778:1 Refused to apply style from 'https://office.mydomain.nl/apps/libresign/css/icons.css?v=955f830b-0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Office.vue:338 Document loading failed due to timeout: Please check for failing network requests

No errors in

**Comment by DaanSelen** [comment]
Ah I see, I said nothing. Hopefully it will be picked up by the Nextcloud/Collabora maintainers

**Comment by gpolydoros** [comment]
> @gpolydoros I do not know if it is the same issue, we see some kind of timeout, which I do not see in your error log. But welcome.

I do have get a timeout error actually, "Document loading failed due to timeout: Please check for failing network requests". It's the last line in my log export :)
 
Can't tell if its the same issue or not though - all I know is that it worked fine until very recently, and now suddenly it's not.

I am running Docker on Debian with Nextcloud and Collabora as containers on the same machine.

**Comment by DaanSelen** [comment]
I think we all suffer the same bug.

**Comment by gpolydoros** [comment]
OK, looking at my own logs again more carefully, I noticed that the requested URL is actually collabora/.domain/.com/, with a slash before every dot. These slashes certainly shouldn't be there.

I remember that when setting up my Collabora docker instance, it required a few environment variables to work (namely, server_name and aliasgroup1, with server_name being my Collabora URL and aliasgroup1 being my Nextcloud URL.  

Both URLs needed to be escaped accordingly in order to work (i.e. nextcloud\.domain\.com and collabora\.domain\.com).

This had worked fine until very recently, but now (maybe after a Collabora update - I don't really know as I use watchtower to handle Docker image updates automatically) it appears that those backslashes are instead converted to forward slashes, resulting in something like i.e. collabora/.domain/.com.

So, I decided to remove the backslashes from both environment variables in my Docker compose file just to test my theory and, to my surprise, Nextcloud now loads the documents correctly.

**Comment by DaanSelen** [comment]
> OK, looking at my own logs again more carefully, I noticed that the requested URL is actually collabora/.domain/.com/, with a slash before every dot. These slashes certainly shouldn't be there.
> 
> I remember that when setting up my Collabora docker instance, it required a few environment variables to work, namely server_name and aliasgroup1, with server_name being my Collabora URL and aliasgroup1 being my Nextcloud URL.
> 
> Both URLs needed to be escaped accordingly in order to work (i.e. nextcloud[\].domain[\].com and collabora[\].domain[\].com).
> 
> This had worked fine until very recently, but now (maybe after a Collabora update - I don't really know as I use watchtower to handle Docker image updates automatically) it appears that those backslashes are instead converted to forward slashes, resulting in something like i.e. collabora[/].domain[/].com.
> 
> So, I decided to remove the backslashes from both environment variables in my Docker compose file just to test my theory and, to my surprise, Nextcloud now loads the documents correctly.

Can confirm, this does fix the issue! My document loads again!

**Comment by gpolydoros** [comment]
> > OK, looking at my own logs again more carefully, I noticed that the requested URL is actually collabora/.domain/.com/, with a slash before every dot. These slashes certainly shouldn't be there.
> > I remember that when setting up my Collabora docker instance, it required a few environment variables to work, namely server_name and aliasgroup1, with server_name being my Collabora URL and aliasgroup1 being my Nextcloud URL.
> > Both URLs needed to be escaped accordingly in order to work (i.e. nextcloud[].domain[].com and collabora[].domain[].com).
> > This had worked fine until very recently, but now (maybe after a Collabora update - I don't really know as I use watchtower to handle Docker image updates automatically) it appears that those backslashes are instead converted to forward slashes, resulting in something like i.e. collabora[/].domain[/].com.
> > So, I decided to remove the backslashes from both environment variables in my Docker compose file just to test my theory and, to my surprise, Nextcloud now loads the documents correctly.
> 
> Can confirm, this does fix the issue! My document loads again!

Nice to know and glad I helped!

This actually confirms that something has indeed changed in the way the Collabora container parses its environment variables.

Last CODE update was 3 days ago, so this is most probably when this change was introduced.

**Comment by Lennyz1988** [comment]
Can you guys post your docker config?

**Comment by juliushaertl** [comment]
This should have been addressed by https://github.com/CollaboraOnline/online/issues/9948
