### ISSUE TITLE
Nextcloud AIO | Office | External Storage | Popup: "Can't save document, please check permissions

### ISSUE THREAD

**Issue by tobias0409** [nextcloud/richdocuments#3971]
**Describe the bug**
Hey,

I have reported the issue also here in the nextcloud forum: https://help.nextcloud.com/t/nextcloud-aio-office-external-storage-popup-cant-save-document-please-check-permissions/202429

If you need further informations, please let me know. I am a new to Nextcloud

I have installed a new version of NC AIO. Next, I have activated the external storage app and connected bmy NAS shares with my NC over SMB (global credentials).

Now to my “problem”: If I create a new document in a external storage folder, I can open it normally and write. However, if I want to save the document, I get an popup with a error message saying: “you can’t save the document, check you permission”. I noticed that the popup is misleading, since the content is indeed saved correctly (reopen the file and the content is there). Since I can access all external storage folders without any issues, I guess the problem (permission etc.) is not there.

Note: If i create a document NOT on a external storage folder, I don’t get the popup.

**Expected behavior**
No popup. The rest is working fine!

**Screenshots**
![grafik](https://github.com/user-attachments/assets/7c453c1f-d9b0-40d6-812f-0affb48bdabe)

**Client details:**
 - OS: Windows 10
 - Browser Firefox
 - Version 129.0.2
 - Device: Desktop

## Server details

**Operating system**: Proxmox / Ubuntu VM with Docker

Everything below is the newest nexcloud AIO version from 01.09.2024

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

**Configuration of the richdocuments app**

```
{
    "apps": {
        "richdocuments": {
            "installed_version": "8.4.5",
            "types": "prevent_group_restriction",
            "enabled": "yes",
            "wopi_callback_url": "",
            "wopi_allowlist": "10.10.10.102, 10.10.10.101,127.0.0.1\/8,192.168.0.0\/16,172.16.0.0\/12,10.0.0.0\/8,fd00::\/8,::1",
            "public_wopi_url": "https:\/\/nextcloud.XXX.at",
            "wopi_url": "https:\/\/nextcloud.XXX.at",
            "use_groups": "",
            "external_apps": "",
            "disable_certificate_verification": ""
        }
    }
}

```

In the Collabora Container I get following error:

```
2024-09-03T12:53:35.856110619Z wsd-00006-15633 2024-09-03 14:53:35.855962 +0200 [ docbroker_00b ] ERR  Failed to upload docKey [https%3A%2F%2Fnextcloud.XXX.at%3A443%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F279757_ocva9f74o662] to URI [https://nextcloud.XXX.at/index.php/apps/richdocuments/wopi/files/279757_ocva9f74o662?access_token=KQAqgmdyx0AAiDSduR25dyJYgSIHR0B1&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:2350
```

**Comment by zEdS15B3GCwq** [comment]
Hello, I'm experiencing the same thing, though only sporadically. When I open a document in an external storage location (SMB server on the same machine), I repeatedly get the same popup about not having permissions. I assume that my CODE is configured to autosave the document, that's why I'm getting the message many times. The SMB permissions are set up correctly, as besides CODE I am able to modify the documents on the storage.

I haven't tested it extensively, but this behaviour doesn't seem to happen all the time. Sometimes I was able to successfully save changes to the document regardless. It has also happened that I didn't get any popups for the same document any more after logging out and in.

Nextcloud AIO v9.4.1 on latest channel, Nextcloud Hub 8 29.0.4, on Debian 12 jail on TrueNAS Scale, behind cloudflare tunnel. The SMB drive is shared by TrueNAS.

**Comment by roelofz** [comment]
Same here: Nextcloud AIO v9.4.1 on latest channel, Nextcloud Hub 8 29.0.4
It looks like it only happens with calc sheets, I did not notice it in a text document.
For me it also has to do with external storage.

**Comment by juliushaertl** [comment]
Can you check if updating to 29.0.5 solves this issue for you?

This sounds like a bug that could have been fixed with https://github.com/nextcloud/server/pull/46679

**Comment by tobias0409** [comment]
I updated my Nextcloud AIO instance to v9.5.1 and the issue seems to be resolved. Thank you!

**Comment by roelofz** [comment]
I updated too yesterday and it looks fixed in 29.06

**Comment by tatrapikao** [comment]
This issue seems to be spreed all over the place:

https://github.com/nextcloud/richdocuments/issues/3971
https://github.com/nextcloud/richdocuments/issues/4032
https://github.com/CollaboraOnline/online/issues/9328

I am on 29.0.6.1 and still affected. as mentioned here: https://github.com/nextcloud/richdocuments/issues/4032#issuecomment-2351538181

**Comment by juliushaertl** [comment]
@tatrapikao Your issue seems different also from the error message, so I'll close this as together with external storage this was reported back as fixed by the initial reporter.
