### ISSUE TITLE
new documents opens in wrong app

### ISSUE THREAD

**Issue by jasondaigo** [nextcloud/richdocuments#679]
**Describe the bug**
When i create a new spreadsheet or presentation a new text document opens in Collabora. Old spreadsheets are not affected. The issue might be related to todays Nextcloud Collabora App update.

**To Reproduce**
1. Go to 'files app'
2. Click on + 
3. Choose 'new spreadsheet (or presentation)'
4. new  text (word)document opens in collabora showing the text 'sdfsd'

**Expected behavior**
the collabora spreadsheet app should start instead of text app. The file extension appears correct, in this case ods.

**Screenshots**

**Client details:**
 - OS: Win 7
 - Chrome 
 - Version 78.0.3904.87
 - Device: 

## Server details

**Operating system**:Ubuntu 18.04

**Web server:**Nginx

**Database:**MariaDB

**PHP version:**7.1

**Nextcloud version:** 16.0.5

**Version of the richdocuments app**:3.4.3

**Version of Collabora Online** 6.0-29 

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```

```

#### Browser log
```

```

</details>

**Comment by t-markmann** [comment]
I have the same error since yesterday with Collabora 3.4.3.
The problem seems to be, that Collabora takes the wrong template.

I fixed this with a rollback to 3.4.2 and rename the templates in /assets to odstemplate.ods odptemplate.odp and odttemplate.odt

The old odttemplate.odt file contains the above mentioned string "sdfsd"

EDIT: you can reproduce this in the official Nextcloud demo as well. Install Collabora, create test office files. You will see that all files have the same size and when downloaded your local Libre Office will open everything in Writer.

**Comment by lutoma** [comment]
This is caused by a10f76fd7baa9e96ed598abd532522aa2859967d / pull request #670, reverting that fixes it. Presumably because that commit removes the previous logic that selected the template based on the mime type, and instead just hardcodes it to ODT.

ping @juliushaertl

**Comment by jasondaigo** [comment]
juts installed update 3.4.4 and issue is indeed gone. thank you

**Comment by juliushaertl** [comment]
Thanks @lutoma for pointing out the faulty commit :+1:
