### ISSUE TITLE
Saved with error: Collabora Online should use the same protocol as the server installation.

### ISSUE THREAD

**Issue by p-baum** [nextcloud/richdocuments#752]
**Describe the bug**
My reverse proxy (Traefik) takes care of SSL.  When i try to put an https address in the 'URL (and Port) of Collabora Online-server' settings i get the error 'Saved with error: Collabora Online should use the same protocol as the server installation.'

1. Why is this even being checked? I'm the admin - I choose.
2. Is the error fatal? Cos I cant get this working!

**To Reproduce**
1. Install behind reverse proxy that handles SSL.
2. Set nextcloud option:   'overwriteprotocol' => 'https'
3. try it

**Expected behavior**
it works

**Client details:**
- plugin: 3.50
 - Browser: firefox latest

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**
17.01

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by p-baum** [comment]
browser console is logging:

´Blocked loading mixed active content “http://mylooldomain:9980/..."´

I have entered the url with https - "saved with error"? 
I dont get it.  Just let me force the scheme i want.

**Comment by j-tai** [comment]
I believe the issue here is that Collabora doesn't consider the possibility that Nextcloud is running behind a reverse proxy. It thinks it is running over HTTP and assumes that Collabora should be as well.

The workaround I am using is to run **both** Nextcloud and Collabora over HTTPS with a self-signed certificate, and disable certificate checking in my reverse proxy (e.g. `proxy_ssl_verify off;` for nginx).

**Comment by juliushaertl** [comment]
> ´Blocked loading mixed active content “http://mylooldomain:9980/..."´

If you access your nextcloud domain through ssl you should also configure collabora to be acessible though ssl. This is why the warning appears.

**Comment by juliushaertl** [comment]
In case the public url is not reachable from within your Nextcloud host, you can also configure a different public_wopi_url app config value.

**Comment by Grk0** [comment]
@juliushaertl: How do I "configure collabora to be acessible though ssl"? Specifically: I am using the official [Nextcloud Docker image](https://hub.docker.com/_/nextcloud/) (20-apache, which is currently stable) and the Built-In CODE server.

**Comment by juliushaertl** [comment]
For setup related questions I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by nZeus** [comment]
Hi, I see the issue is 2yo... And instead of fixing it, you just closed it... Big disappointment guys

**Comment by juliushaertl** [comment]
Maybe to make it more clear, this is nothing that we can even fix. Mixed protocols are blocked by browser policies, so if we would allow to configure a http collabora url with a https nextcloud, browsers would block the access.

We use GitHub for bug tracking and not setup support, that is why I asked to move over to the forum for setup and configuration related questions.

**Comment by winux1337** [comment]
maybe it is usefull for your problem.

description of my installation:

    debian bullseye
    Apache
    php 8.0
    nextcloud 24
    behind FireWall
    OpnSense
    ReverseProxy based on apache with Let’s entcrypt (on Raspberry)

I had the same error “collabora should use the same protocol as the server” and solved this with the follow entry in the ReverseProxy config.

sorry, i can’t show you my config, because i am a new user and i am can post only four links ;(

i found this in ([document-server-proxy/proxy-https-to-http.conf at master · ONLYOFFICE/document-server-proxy · GitHub](https://github.com/ONLYOFFICE/document-server-proxy/blob/master/apache/proxy-https-to-http.conf)) line 40 - 47

Best regards
Winux

I posted this in the nextcloud community too:
https://help.nextcloud.com/t/error-collabora-online-should-use-the-same-protocol-as-the-server-installation/45639/15

**Comment by juliushaertl** [comment]
Anyone having this issue may want to check the ssl.enable and ssl.termination configuration inside of the coolwsd.xml file. 

Detailed documentation is available at: https://sdk.collaboraonline.com/docs/installation/Configuration.html#ssl-configuration

A small improvement on the error reporting within richdocuments is pushed with https://github.com/nextcloud/richdocuments/pull/2371

**Comment by albjeremias** [comment]
This error was not happening in previous versions of nextcloud docker images. So I want to try to understand better whats is going on... can we automate it using docker? to change the coolswd.xml file?

 I can try to troubleshoot and provide a solution to github.. its anoying im behind a reverse proxy using docker-compose ... 

![image](https://user-images.githubusercontent.com/26681446/196686803-06a1a7ca-4031-41fe-b85e-8140b1279e17.png)
