### ISSUE TITLE
3.6.0 Demo server feature - timeout

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#953]
I think we used to have a timeout function in richdocuments, but apparently it's not triggered in the case when the demo server does not respond. 

Probably after 10 seconds richdocuments should give up and display a message:

Could not load the document editor. Either the server is busy, or there is a connection problem. 

If you use a public demo server, please make sure that your Nextcloud host is accessible from the Internet. Otherwise try later.

**Comment by juliushaertl** [comment]
It should actually do that if no loading post message is received within 15 seconds:

https://github.com/nextcloud/richdocuments/blob/master/src/viewer.js#L146-L151
https://github.com/nextcloud/richdocuments/blob/master/src/viewer.js#L445

> If you use a public demo server, please make sure that your Nextcloud host is accessible from the Internet. Otherwise try later.

Yes, that could be an issue and we should properly state that.

**Comment by mmeeks** [comment]
This is an issue if you run a local http://localhost/nextcloud type server and then connect to a demo server - we get a CSP violation and just a grey screen, it's quite funky =)

**Comment by juliushaertl** [comment]
I guess https://github.com/nextcloud/richdocuments/pull/958 solves the main issue that you can setup such a non-working connection then. 

For the CSP error, it should actually not happen (after the files app has been reloaded when setting the demo server) since the Collabora Server domain will then be set as trusted host for iframes in the request.
