### ISSUE TITLE
Collabora Online not setup yet

### ISSUE THREAD

**Issue by alijundi** [nextcloud/richdocuments#972]
I receive the above message even though the server is setup correctly and to be more precise it was working perfectly on version 3.5.3 (Earlier one).

Any idea how to fix this issue?

**Comment by tjareson** [comment]
Same here. It comes with the same issue since 3.6.0. Updated collabora docker container, no change. 
In the log of the collarbora container I see issues like: 

wsd-00006-00036 2020-05-17 19:52:24.910814 [ websrv_poll ] ERR  Socket #21 SSL BIO error: closed unexpectedly (-1). (0: Success)| ./net/SslSocket.hpp:278
wsd-00006-00036 2020-05-17 19:52:24.914836 [ websrv_poll ] ERR  Error while handling poll for socket #21 in websrv_poll: SSL Socket closed unexpectedly.| net/Socket.cpp:308

**Comment by thebearon** [comment]
Please check #949, especially [this comment](https://github.com/nextcloud/richdocuments/issues/949#issuecomment-627155533).
